version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./clubunit.kr.pem:/etc/nginx/ssl/clubunit.kr.pem
      - ./clubunit.kr-key.pem:/etc/nginx/ssl/clubunit.kr-key.pem
    ports:
      - "443:443"
