#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏛🏛🏛🏛... Before push, Trying to build now. 🏛🏛🏛🏛'

pnpm run build ||
(
    echo '❌👷🔨❌ Your production build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false;
)

echo '✅✅✅✅ You win this time... I am pushing this now. ✅✅✅✅'
